# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install all dependencies including dev
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

# Copy source and build
COPY src ./src
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install production deps only, skip scripts
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Copy built files
COPY --from=builder /app/build ./build

# Default command will be supplied by startCommand
